version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: office_manager_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - office_network

  adminer:
    image: adminer:latest
    container_name: office_manager_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - office_network

volumes:
  postgres_data:

networks:
  office_network:
    driver: bridge